query documents{
    documentForUser {
        id
        createdAt
        updatedAt
        user{
            firstName
            lastName
            email
        }
        status
        filePath
        file{
            filename
            contentType
            byteSize
        }
    }
}